name: Daily Python Script

on:
  schedule:
    - cron: '50 4 * * *'  # 7:01 AM Italy time during summer

  workflow_dispatch:     # Allows manual triggering from the GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
        
    - name: Wait until 7:01 AM CEST if earlier
      run: |
        echo "Checking current time in Europe/Rome timezone..."
        current_time=$(TZ=Europe/Rome date +%H:%M)
        target_time="07:01"
    
        if [[ "$current_time" < "$target_time" ]]; then
          echo "Current time ($current_time) is before $target_time. Waiting..."
          while [ "$(TZ=Europe/Rome date +%H:%M)" != "$target_time" ]; do
            sleep 5
          done
        else
          echo "Current time ($current_time) is after $target_time. Continuing without wait."
        fi

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Only needed if you have this file

    - name: Run script
      run: |
        python biblio_booking.py
    
    - name: Read codice prenotazione fede
      if: success()
      id: codice_fede
      run: echo "codice_fede=$(cat codice_fede.txt)" >> "$GITHUB_OUTPUT"

    - name: Read codice prenotazione nico
      if: success()
      id: codice_nico
      run: echo "codice_nico=$(cat codice_nico.txt)" >> "$GITHUB_OUTPUT"

    - name: Read codice prenotazione marghe
      if: success()
      id: codice_marghe
      run: echo "codice_marghe=$(cat codice_marghe.txt)" >> "$GITHUB_OUTPUT"

    - name: Send Telegram notification for fede
      if: success()
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
          -d chat_id=$TELEGRAM_CHAT_ID \
          -d text="✅ Daily Python script completed successfully at $(TZ=Europe/Rome date). Codice prenotazione fede: ${{ steps.codice_fede.outputs.codice_fede }}"

    - name: Send Telegram notification for nico
      if: success()
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
          -d chat_id=$TELEGRAM_CHAT_ID \
          -d text="✅ Daily Python script completed successfully at $(TZ=Europe/Rome date). Codice prenotazione nico: ${{ steps.codice_nico.outputs.codice_nico }}"

    - name: Send Telegram notification for marghe
      if: success()
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
          -d chat_id=$TELEGRAM_CHAT_ID \
          -d text="✅ Daily Python script completed successfully at $(TZ=Europe/Rome date). Codice prenotazione marghe: ${{ steps.codice_marghe.outputs.codice_marghe }}"

    - name: Send Telegram failure notification
      if: failure()
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
          -d chat_id=$TELEGRAM_CHAT_ID \
          -d text="❌ Daily Python script *failed* at $(TZ=Europe/Rome date)." \
          -d parse_mode=Markdown




