name: Daily Python Script

on:
  schedule:
    - cron: '20 10 * * *'  # 7:01 AM Italy time during summer

  workflow_dispatch:     # Allows manual triggering from the GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Change if needed

    - name: Run script
      run: |
        python biblio_booking.py
